spring:
  application:
    name: couple

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: none

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 300000

logging:
  level:
    org.springframework.security: INFO